2025-02-27 10:27:29,990 - INFO - DatabaseService - Database connection pool closed.
2025-02-27 10:27:36,276 - INFO - DatabaseService - Database connection pool closed.
2025-02-27 10:27:36,330 - INFO - DatabaseService - Database connection pool closed.
2025-02-27 10:27:36,372 - INFO - DatabaseService - Database connection pool closed.
2025-02-27 10:27:36,448 - INFO - DatabaseService - Database connection pool closed.
2025-02-27 10:27:36,607 - INFO - DatabaseService - Database connection pool closed.
2025-02-27 10:27:36,663 - INFO - DatabaseService - Database connection pool closed.
2025-02-27 10:27:36,823 - INFO - DatabaseService - Database connection pool closed.
2025-02-27 10:27:36,867 - INFO - DatabaseService - Database connection pool closed.
2025-02-27 10:27:36,870 - INFO - DatabaseService - Database connection pool closed.
2025-02-27 10:27:38,142 - INFO - DatabaseService - Database connection pool closed.
2025-02-27 10:27:38,144 - INFO - DatabaseService - Database connection pool closed.
2025-02-27 10:27:38,146 - INFO - DatabaseService - Database connection pool closed.
2025-02-27 10:27:38,149 - INFO - DatabaseService - Database connection pool closed.
2025-02-27 10:27:41,710 - INFO - DatabaseService - Database connection pool closed.
2025-02-27 10:27:41,712 - INFO - DatabaseService - Database connection pool closed.
2025-02-27 10:27:41,713 - INFO - DatabaseService - Database connection pool closed.
2025-02-27 10:27:41,714 - INFO - DatabaseService - Database connection pool closed.
2025-02-27 10:27:41,715 - INFO - DatabaseService - Database connection pool closed.
2025-02-27 10:27:41,997 - INFO - DatabaseService - Database connection pool closed.
2025-02-27 10:27:41,999 - INFO - DatabaseService - Database connection pool closed.
2025-02-27 10:27:42,001 - INFO - DatabaseService - Database connection pool closed.
2025-02-27 10:27:42,003 - INFO - DatabaseService - Database connection pool closed.
2025-02-27 10:27:42,004 - INFO - DatabaseService - Database connection pool closed.
2025-02-27 10:27:44,314 - INFO - DatabaseService - Database connection pool closed.
2025-02-27 11:45:45,532 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 11:46:21,292 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 11:47:14,852 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 11:49:33,071 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 11:49:55,308 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 11:50:50,929 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 11:52:25,516 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 11:52:47,012 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 11:54:21,031 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 11:54:38,053 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 11:55:23,245 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 11:55:39,657 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 11:55:53,205 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 11:56:24,606 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 11:56:36,911 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 11:56:54,612 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 11:58:36,650 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 11:59:25,651 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:00:05,657 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:01:23,345 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:01:36,905 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:02:17,966 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:03:00,842 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:04:45,011 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:04:56,048 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:05:49,044 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:09:42,976 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:11:13,551 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:12:41,483 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:13:57,119 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:16:00,231 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:18:18,982 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:19:04,761 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:20:08,704 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:20:25,249 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:20:25,309 - ERROR - DatabaseService - Error exequting the query: DELETE FROM users WHERE username = 'new_user'. <Error> Task <Task pending name='Task-17' coro=<test_create_user() running at C:\Users\danie\Projects\journal\backend\tests\test_users.py:5> cb=[_run_until_complete_cb() at C:\Users\danie\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:182]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop
2025-02-27 12:22:49,849 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:22:49,908 - ERROR - DatabaseService - Error exequting the query: DELETE FROM users WHERE username = 'new_user'. <Error> Task <Task pending name='Task-17' coro=<test_create_user() running at C:\Users\danie\Projects\journal\backend\tests\test_users.py:5> cb=[_run_until_complete_cb() at C:\Users\danie\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:182]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop
2025-02-27 12:23:00,036 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:24:28,745 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:24:29,439 - ERROR - DatabaseService - Error exequting the query: DELETE FROM users WHERE username = 'new_user'. <Error> Task <Task pending name='Task-40' coro=<_wrap_asyncgen_fixture.<locals>._asyncgen_fixture_wrapper.<locals>.finalizer.<locals>.async_finalizer() running at c:\Users\danie\AppData\Local\pypoetry\Cache\virtualenvs\app-jcRBtVaX-py3.12\Lib\site-packages\pytest_asyncio\plugin.py:338> cb=[_run_until_complete_cb() at C:\Users\danie\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:182]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop
2025-02-27 12:25:44,254 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:25:44,957 - ERROR - DatabaseService - Error exequting the query: DELETE FROM users WHERE username = 'new_user'. <Error> Task <Task pending name='Task-40' coro=<_wrap_asyncgen_fixture.<locals>._asyncgen_fixture_wrapper.<locals>.finalizer.<locals>.async_finalizer() running at c:\Users\danie\AppData\Local\pypoetry\Cache\virtualenvs\app-jcRBtVaX-py3.12\Lib\site-packages\pytest_asyncio\plugin.py:338> cb=[_run_until_complete_cb() at C:\Users\danie\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:182]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop
2025-02-27 12:26:10,813 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:26:11,515 - ERROR - DatabaseService - Error exequting the query: DELETE FROM users WHERE username = 'new_user'. <Error> Task <Task pending name='Task-40' coro=<_wrap_asyncgen_fixture.<locals>._asyncgen_fixture_wrapper.<locals>.finalizer.<locals>.async_finalizer() running at c:\Users\danie\AppData\Local\pypoetry\Cache\virtualenvs\app-jcRBtVaX-py3.12\Lib\site-packages\pytest_asyncio\plugin.py:338> cb=[_run_until_complete_cb() at C:\Users\danie\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:182]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop
2025-02-27 12:27:47,484 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:29:33,139 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:29:33,844 - ERROR - DatabaseService - Error exequting the query: DELETE FROM users WHERE username LIKE '%user%'. <Error> Task <Task pending name='Task-40' coro=<_wrap_asyncgen_fixture.<locals>._asyncgen_fixture_wrapper.<locals>.finalizer.<locals>.async_finalizer() running at c:\Users\danie\AppData\Local\pypoetry\Cache\virtualenvs\app-jcRBtVaX-py3.12\Lib\site-packages\pytest_asyncio\plugin.py:338> cb=[_run_until_complete_cb() at C:\Users\danie\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:182]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop
2025-02-27 12:29:42,362 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:30:53,231 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:31:30,930 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:32:04,550 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:32:04,760 - ERROR - DatabaseService - Error fetching one value: SELECT a+a. <Error> column "a" does not exist
2025-02-27 12:32:48,210 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:34:01,462 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:35:13,591 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:35:52,954 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:37:46,138 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:39:11,421 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:49:38,490 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:49:38,801 - ERROR - DatabaseService - Error fetching row: INSERT INTO users (username, email, password) VALUES ($1, $2, $3) RETURNING *. <Error> duplicate key value violates unique constraint "users_pkey"
DETAIL:  Key (id)=(1) already exists.
2025-02-27 12:51:08,061 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:51:08,382 - ERROR - DatabaseService - Error fetching row: INSERT INTO users (username, email, password) VALUES ($1, $2, $3) RETURNING *. <Error> duplicate key value violates unique constraint "users_pkey"
DETAIL:  Key (id)=(1) already exists.
2025-02-27 12:52:05,404 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:52:05,609 - ERROR - DatabaseService - Error fetching row: INSERT INTO users (username, email, password) VALUES ($1, $2, $3) RETURNING *. <Error> duplicate key value violates unique constraint "users_pkey"
DETAIL:  Key (id)=(1) already exists.
2025-02-27 12:52:27,584 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:52:27,790 - ERROR - DatabaseService - Error fetching row: INSERT INTO users (username, email, password) VALUES ($1, $2, $3) RETURNING *. <Error> duplicate key value violates unique constraint "users_pkey"
DETAIL:  Key (id)=(1) already exists.
2025-02-27 12:53:25,363 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:53:25,783 - ERROR - DatabaseService - Error fetching row: INSERT INTO users (username, email, password) VALUES ($1, $2, $3) RETURNING *. <Error> duplicate key value violates unique constraint "users_pkey"
DETAIL:  Key (id)=(1) already exists.
2025-02-27 12:54:51,453 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:56:29,578 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:57:34,063 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 12:57:34,273 - ERROR - DatabaseService - Error fetching row: INSERT INTO users (username, email, password) VALUES ($1, $2, $3) RETURNING *. <Error> duplicate key value violates unique constraint "users_pkey"
DETAIL:  Key (id)=(1) already exists.
2025-02-27 13:01:05,097 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:01:05,319 - ERROR - DatabaseService - Error fetching row: INSERT INTO users (username, email, password) VALUES ($1, $2, $3) RETURNING *. <Error> duplicate key value violates unique constraint "users_pkey"
DETAIL:  Key (id)=(1) already exists.
2025-02-27 13:02:48,226 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:02:48,641 - ERROR - DatabaseService - Error fetching row: INSERT INTO users (username, email, password) VALUES ($1, $2, $3) RETURNING *. <Error> duplicate key value violates unique constraint "users_pkey"
DETAIL:  Key (id)=(1) already exists.
2025-02-27 13:04:03,201 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:04:03,521 - ERROR - DatabaseService - Error fetching row: INSERT INTO users (username, email, password) VALUES ($1, $2, $3) RETURNING *. <Error> duplicate key value violates unique constraint "users_pkey"
DETAIL:  Key (id)=(1) already exists.
2025-02-27 13:05:18,096 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:05:18,312 - ERROR - DatabaseService - Error fetching row: INSERT INTO users (username, email, password) VALUES ($1, $2, $3) RETURNING *. <Error> duplicate key value violates unique constraint "users_pkey"
DETAIL:  Key (id)=(1) already exists.
2025-02-27 13:07:29,754 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:07:30,288 - ERROR - DatabaseService - Error fetching row: INSERT INTO users (username, email, password) VALUES ($1, $2, $3) RETURNING *. <Error> duplicate key value violates unique constraint "users_pkey"
DETAIL:  Key (id)=(1) already exists.
2025-02-27 13:07:52,070 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:07:52,290 - ERROR - DatabaseService - Error fetching row: INSERT INTO users (username, email, password) VALUES ($1, $2, $3) RETURNING *. <Error> duplicate key value violates unique constraint "users_pkey"
DETAIL:  Key (id)=(1) already exists.
2025-02-27 13:09:05,796 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:09:06,133 - ERROR - DatabaseService - Error fetching row: INSERT INTO users (username, email, password) VALUES ($1, $2, $3) RETURNING *. <Error> duplicate key value violates unique constraint "users_pkey"
DETAIL:  Key (id)=(1) already exists.
2025-02-27 13:09:18,769 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:09:19,096 - ERROR - DatabaseService - Error fetching row: INSERT INTO users (username, email, password) VALUES ($1, $2, $3) RETURNING *. <Error> duplicate key value violates unique constraint "users_pkey"
DETAIL:  Key (id)=(1) already exists.
2025-02-27 13:12:33,439 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:12:33,875 - ERROR - DatabaseService - Error fetching row: INSERT INTO users (username, email, password) VALUES ($1, $2, $3) RETURNING *. <Error> duplicate key value violates unique constraint "users_pkey"
DETAIL:  Key (id)=(1) already exists.
2025-02-27 13:13:10,187 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:13:10,507 - ERROR - DatabaseService - Error fetching row: INSERT INTO users (username, email, password) VALUES ($1, $2, $3) RETURNING *. <Error> duplicate key value violates unique constraint "users_pkey"
DETAIL:  Key (id)=(1) already exists.
2025-02-27 13:14:06,088 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:14:06,253 - ERROR - DatabaseService - Error fetching row: INSERT INTO users (username, email, password) VALUES ($1, $2, $3) RETURNING *. <Error> duplicate key value violates unique constraint "users_pkey"
DETAIL:  Key (id)=(1) already exists.
2025-02-27 13:14:06,861 - ERROR - DatabaseService - Error exequting the query: DELETE FROM users. <Error> Task <Task pending name='Task-45' coro=<_wrap_asyncgen_fixture.<locals>._asyncgen_fixture_wrapper.<locals>.finalizer.<locals>.async_finalizer() running at c:\Users\danie\AppData\Local\pypoetry\Cache\virtualenvs\app-jcRBtVaX-py3.12\Lib\site-packages\pytest_asyncio\plugin.py:338> cb=[_run_until_complete_cb() at C:\Users\danie\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:182]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop
2025-02-27 13:14:16,624 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:14:16,789 - ERROR - DatabaseService - Error fetching row: INSERT INTO users (username, email, password) VALUES ($1, $2, $3) RETURNING *. <Error> duplicate key value violates unique constraint "users_pkey"
DETAIL:  Key (id)=(1) already exists.
2025-02-27 13:14:17,394 - ERROR - DatabaseService - Error exequting the query: DELETE FROM users. <Error> Task <Task pending name='Task-45' coro=<_wrap_asyncgen_fixture.<locals>._asyncgen_fixture_wrapper.<locals>.finalizer.<locals>.async_finalizer() running at c:\Users\danie\AppData\Local\pypoetry\Cache\virtualenvs\app-jcRBtVaX-py3.12\Lib\site-packages\pytest_asyncio\plugin.py:338> cb=[_run_until_complete_cb() at C:\Users\danie\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:182]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop
2025-02-27 13:14:26,691 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:14:26,854 - ERROR - DatabaseService - Error fetching row: INSERT INTO users (username, email, password) VALUES ($1, $2, $3) RETURNING *. <Error> duplicate key value violates unique constraint "users_pkey"
DETAIL:  Key (id)=(1) already exists.
2025-02-27 13:14:27,459 - ERROR - DatabaseService - Error exequting the query: DELETE FROM users. <Error> Task <Task pending name='Task-45' coro=<_wrap_asyncgen_fixture.<locals>._asyncgen_fixture_wrapper.<locals>.finalizer.<locals>.async_finalizer() running at c:\Users\danie\AppData\Local\pypoetry\Cache\virtualenvs\app-jcRBtVaX-py3.12\Lib\site-packages\pytest_asyncio\plugin.py:338> cb=[_run_until_complete_cb() at C:\Users\danie\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:182]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop
2025-02-27 13:14:52,040 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:14:52,216 - ERROR - DatabaseService - Error fetching row: INSERT INTO users (username, email, password) VALUES ($1, $2, $3) RETURNING *. <Error> duplicate key value violates unique constraint "users_pkey"
DETAIL:  Key (id)=(1) already exists.
2025-02-27 13:14:52,848 - ERROR - DatabaseService - Error exequting the query: DELETE FROM users. <Error> Task <Task pending name='Task-45' coro=<_wrap_asyncgen_fixture.<locals>._asyncgen_fixture_wrapper.<locals>.finalizer.<locals>.async_finalizer() running at c:\Users\danie\AppData\Local\pypoetry\Cache\virtualenvs\app-jcRBtVaX-py3.12\Lib\site-packages\pytest_asyncio\plugin.py:338> cb=[_run_until_complete_cb() at C:\Users\danie\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:182]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop
2025-02-27 13:15:19,221 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:15:19,387 - ERROR - DatabaseService - Error fetching row: INSERT INTO users (username, email, password) VALUES ($1, $2, $3) RETURNING *. <Error> duplicate key value violates unique constraint "users_pkey"
DETAIL:  Key (id)=(1) already exists.
2025-02-27 13:15:19,992 - ERROR - DatabaseService - Error exequting the query: TRUNCATE TABLE users. <Error> Task <Task pending name='Task-45' coro=<_wrap_asyncgen_fixture.<locals>._asyncgen_fixture_wrapper.<locals>.finalizer.<locals>.async_finalizer() running at c:\Users\danie\AppData\Local\pypoetry\Cache\virtualenvs\app-jcRBtVaX-py3.12\Lib\site-packages\pytest_asyncio\plugin.py:338> cb=[_run_until_complete_cb() at C:\Users\danie\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:182]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop
2025-02-27 13:17:35,039 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:17:35,051 - ERROR - DatabaseService - Error fetching row: DELETE users WHERE username='test. <Error> syntax error at or near "users"
2025-02-27 13:17:48,380 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:17:48,391 - ERROR - DatabaseService - Error fetching row: DELETE FROM users WHERE username='test. <Error> unterminated quoted string at or near "'test"
2025-02-27 13:17:59,033 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:18:39,604 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:19:00,747 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:19:11,360 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:19:11,533 - ERROR - DatabaseService - Error exequting the query: TRUNCATE TABLE users. <Error> Task <Task pending name='Task-48' coro=<_wrap_asyncgen_fixture.<locals>._asyncgen_fixture_wrapper.<locals>.finalizer.<locals>.async_finalizer() running at c:\Users\danie\AppData\Local\pypoetry\Cache\virtualenvs\app-jcRBtVaX-py3.12\Lib\site-packages\pytest_asyncio\plugin.py:338> cb=[_run_until_complete_cb() at C:\Users\danie\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:182]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop
2025-02-27 13:19:52,810 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:20:04,354 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:21:23,763 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:21:23,838 - ERROR - DatabaseService - Error fetching row: DELETE FROM users WHERE username='test'. <Error> Task <Task pending name='Task-20' coro=<test_remove_users() running at C:\Users\danie\Projects\journal\backend\tests\test_users.py:58> cb=[_run_until_complete_cb() at C:\Users\danie\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:182]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop
2025-02-27 13:21:58,890 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:21:58,957 - ERROR - DatabaseService - Error fetching row: DELETE FROM users WHERE username='test'. <Error> Task <Task pending name='Task-20' coro=<test_remove_users() running at C:\Users\danie\Projects\journal\backend\tests\test_users.py:59> cb=[_run_until_complete_cb() at C:\Users\danie\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:182]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop
2025-02-27 13:22:23,281 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:24:37,808 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:24:50,959 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:25:51,443 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:26:14,518 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:27:05,764 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:30:50,771 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:31:13,175 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:32:58,971 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:34:08,055 - ERROR - DatabaseService - Error exequting the query: DROP SCHEMA public CASCADE; CREATE SCHEMA public;. <Error> Task <Task pending name='Task-4' coro=<test_create_schema() running at C:\Users\danie\Projects\journal\backend\tests\test_database.py:23> cb=[_run_until_complete_cb() at C:\Users\danie\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:182]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop
2025-02-27 13:36:17,365 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:36:49,281 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:37:30,129 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:38:14,039 - ERROR - DatabaseService - Error exequting the query: DROP SCHEMA public CASCADE; CREATE SCHEMA public;. <Error> Task <Task pending name='Task-4' coro=<test_create_schema() running at C:\Users\danie\Projects\journal\backend\tests\test_database.py:23> cb=[_run_until_complete_cb() at C:\Users\danie\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:182]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop
2025-02-27 13:38:14,628 - ERROR - DatabaseService - Error exequting the query: INSERT INTO users VALUES (1, 'test', 'test@email.com', 'test'). <Error> duplicate key value violates unique constraint "users_pkey"
DETAIL:  Key (id)=(1) already exists.
2025-02-27 13:38:50,215 - ERROR - DatabaseService - Error exequting the query: DROP SCHEMA public CASCADE; CREATE SCHEMA public;. <Error> Task <Task pending name='Task-4' coro=<test_create_schema() running at C:\Users\danie\Projects\journal\backend\tests\test_database.py:23> cb=[_run_until_complete_cb() at C:\Users\danie\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:182]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop
2025-02-27 13:40:46,997 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:42:01,134 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:42:26,520 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:49:02,403 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:49:11,239 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:49:17,932 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:49:58,053 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:50:32,350 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 13:51:26,608 - ERROR - DatabaseService - Error exequting the query: DROP SCHEMA public CASCADE; CREATE SCHEMA public;. <Error> Task <Task pending name='Task-2' coro=<test_create_schema() running at C:\Users\danie\Projects\journal\backend\tests\test_database.py:8> cb=[_run_until_complete_cb() at C:\Users\danie\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:182]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop
2025-02-27 13:51:40,554 - ERROR - DatabaseService - Error exequting the query: DROP SCHEMA public CASCADE; CREATE SCHEMA public;. <Error> Task <Task pending name='Task-2' coro=<test_create_schema() running at C:\Users\danie\Projects\journal\backend\tests\test_database.py:8> cb=[_run_until_complete_cb() at C:\Users\danie\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:182]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop
2025-02-27 13:52:26,796 - ERROR - DatabaseService - Error exequting the query: DROP SCHEMA public CASCADE; CREATE SCHEMA public;. <Error> Task <Task pending name='Task-2' coro=<test_create_schema() running at C:\Users\danie\Projects\journal\backend\tests\test_database.py:8> cb=[_run_until_complete_cb() at C:\Users\danie\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:182]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop
2025-02-27 16:04:26,615 - ERROR - DatabaseService - Error exequting the query: DROP SCHEMA public CASCADE; CREATE SCHEMA public;. <Error> Task <Task pending name='Task-2' coro=<test_create_schema() running at C:\Users\danie\Projects\journal\backend\tests\test_database.py:8> cb=[_run_until_complete_cb() at C:\Users\danie\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:182]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop
2025-02-27 16:04:52,601 - ERROR - DatabaseService - Error exequting the query: DROP SCHEMA public CASCADE; CREATE SCHEMA public;. <Error> Task <Task pending name='Task-2' coro=<test_create_schema() running at C:\Users\danie\Projects\journal\backend\tests\test_database.py:8> cb=[_run_until_complete_cb() at C:\Users\danie\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:182]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop
2025-02-27 16:04:53,304 - ERROR - DatabaseService - Error exequting the query: INSERT INTO users VALUES (1, 'test', 'test@email.com', 'test'). <Error> duplicate key value violates unique constraint "users_pkey"
DETAIL:  Key (id)=(1) already exists.
2025-02-27 16:05:47,509 - ERROR - DatabaseService - Error exequting the query: DROP SCHEMA public CASCADE; CREATE SCHEMA public;. <Error> Task <Task pending name='Task-2' coro=<test_create_schema() running at C:\Users\danie\Projects\journal\backend\tests\test_database.py:8> cb=[_run_until_complete_cb() at C:\Users\danie\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:182]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop
2025-02-27 16:17:22,339 - ERROR - DatabaseService - Error exequting the query: DROP SCHEMA public CASCADE; CREATE SCHEMA public;. <Error> Task <Task pending name='Task-2' coro=<test_create_schema() running at C:\Users\danie\Projects\journal\backend\tests\test_database.py:8> cb=[_run_until_complete_cb() at C:\Users\danie\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:182]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop
2025-02-27 16:18:50,747 - ERROR - DatabaseService - Error exequting the query: DROP SCHEMA public CASCADE; CREATE SCHEMA public;. <Error> Task <Task pending name='Task-2' coro=<test_create_schema() running at C:\Users\danie\Projects\journal\backend\tests\test_database.py:8> cb=[_run_until_complete_cb() at C:\Users\danie\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:182]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop
2025-02-27 16:19:02,806 - ERROR - DatabaseService - Error exequting the query: DROP SCHEMA public CASCADE; CREATE SCHEMA public;. <Error> Task <Task pending name='Task-2' coro=<test_create_schema() running at C:\Users\danie\Projects\journal\backend\tests\test_database.py:8> cb=[_run_until_complete_cb() at C:\Users\danie\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:182]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop
2025-02-27 16:21:52,297 - ERROR - DatabaseService - Error exequting the query: DROP SCHEMA public CASCADE; CREATE SCHEMA public;. <Error> Task <Task pending name='Task-2' coro=<test_create_schema() running at C:\Users\danie\Projects\journal\backend\tests\test_database.py:8> cb=[_run_until_complete_cb() at C:\Users\danie\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:182]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop
2025-02-27 16:22:28,260 - ERROR - DatabaseService - Error exequting the query: DROP SCHEMA public CASCADE; CREATE SCHEMA public;. <Error> Task <Task pending name='Task-2' coro=<test_create_schema() running at C:\Users\danie\Projects\journal\backend\tests\test_database.py:8> cb=[_run_until_complete_cb() at C:\Users\danie\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:182]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop
2025-02-27 16:23:28,198 - ERROR - DatabaseService - Error exequting the query: DROP SCHEMA public CASCADE; CREATE SCHEMA public;. <Error> Task <Task pending name='Task-2' coro=<test_create_schema() running at C:\Users\danie\Projects\journal\backend\tests\test_database.py:8> cb=[_run_until_complete_cb() at C:\Users\danie\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:182]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop
2025-02-27 16:26:13,460 - ERROR - DatabaseService - Error exequting the query: DROP SCHEMA public CASCADE; CREATE SCHEMA public;. <Error> Task <Task pending name='Task-2' coro=<test_create_schema() running at C:\Users\danie\Projects\journal\backend\tests\test_database.py:8> cb=[_run_until_complete_cb() at C:\Users\danie\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:182]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop
2025-02-27 16:26:44,800 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 16:26:57,381 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 16:27:13,353 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 16:27:18,886 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 16:28:51,537 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 16:30:12,211 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 16:30:30,412 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 16:30:41,481 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 16:31:05,829 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 16:31:37,246 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 16:31:57,514 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 16:34:10,193 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 16:36:23,789 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 16:36:44,075 - ERROR - DatabaseService - Error exequting the query: DROP SCHEMA public CASCADE; CREATE SCHEMA public;. <Error> Task <Task pending name='Task-2' coro=<test_create_schema() running at C:\Users\danie\Projects\journal\backend\tests\test_database.py:8> cb=[_run_until_complete_cb() at C:\Users\danie\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:182]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop
2025-02-27 16:36:44,663 - ERROR - DatabaseService - Error fetching one value: SELECT 1+1. <Error> 'NoneType' object has no attribute 'send'
2025-02-27 16:42:48,826 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 16:43:21,155 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 16:43:56,524 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 16:45:07,290 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 16:46:07,716 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 16:47:50,292 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 16:48:15,602 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 16:50:53,116 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 16:52:34,538 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 16:53:34,188 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 16:54:18,139 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 16:57:10,453 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 16:58:30,459 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 17:01:28,317 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 17:02:56,418 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 17:03:19,183 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 17:05:33,235 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 17:09:16,167 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 17:09:51,153 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 17:13:27,344 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 17:14:16,947 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 17:15:26,144 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 17:15:50,521 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 17:16:26,419 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 17:17:45,529 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 17:18:15,470 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 17:18:42,536 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 17:19:31,031 - INFO - DatabaseService - Database schema created successfully.
2025-02-27 17:19:58,767 - INFO - DatabaseService - Database schema created successfully.
